### ISSUE TITLE
ImportError: cannot import name 'ipm' from 'iris' (/usr/irissys/lib/python/iris.py)

### ISSUE THREAD

**Issue by SylvainGuilbaud** [intersystems-community/iris-embedded-python-template#9]
Hello,
after having cloned this template on a Mac M1 (ARM), the docker compose build --no-cache failed during the iris_script.py execution at line 6 : 

#0 23.33 Starting IRIS
#0 23.33 
#0 24.45 
#0 24.45 IRIS Merge completed successfully
#0 25.06 Traceback (most recent call last):
#0 25.06   File "/home/irisowner/dev/iris_script.py", line 6, in <module>
#0 25.06     from iris import ipm
#0 25.06 ImportError: cannot import name 'ipm' from 'iris' (/usr/irissys/lib/python/iris.py)
------
failed to solve: process "/bin/sh -c pip3 install -r requirements.txt &&     iris start IRIS &&     iris merge IRIS merge.cpf &&     irispython iris_script.py &&     iris stop IRIS quietly" did not complete successfully: exit code: 1

The error is the same when using 
ARG IMAGE=containers.intersystems.com/intersystems/iris-community-arm64:latest-cd

NB : another test shows that everything runs fine when using a Mac with Intel CPU.

**Comment by evshvarov** [comment]
Hi @SylvainGuilbaud .
try with ARG IMAGE=intersystemsdc/iris-community image - it adds ipm support into irispython

**Comment by evshvarov** [comment]
@daimor introduced it

**Comment by evshvarov** [comment]
here is the function https://github.com/intersystems-community/zpm-dockerhub/blob/master/iris_ipm.py

and here is how it is being submitted to iris.py https://github.com/intersystems-community/zpm-dockerhub/blob/919fe4ac3fd9cb7c8e286d05ee18a9126564999c/Dockerfile#L97

I think you can do the same trick with official image, or use the community one for dev purposes

**Comment by SylvainGuilbaud** [comment]
Nope ; actually my very first test was with :
ARG IMAGE=intersystemsdc/iris-community
The second test was with :
ARG IMAGE=containers.intersystems.com/intersystems/iris-community-arm64:latest-cd
Both failed

**Comment by evshvarov** [comment]
pull the newer community image?

**Comment by SylvainGuilbaud** [comment]
That was it...
A new pull of the latest community image fixed everything.
Thanks @evshvarov

**Comment by SylvainGuilbaud** [comment]
Issue fixed.

**Comment by evshvarov** [comment]
Glad to hear that!
